NeuroTIC: /home/titux/DEV/NeuroTIC/NeuroTIC/src/CPU/ntactivation.c File Reference
ntactivation.c File Reference
Internal implementation of activation behavior.
#include "ntactivation.h"
#include <math.h>
Functions
static float boolean (float x)
static float boolean_d (float x)
static float sigmoid (float x)
static float sigmoid_d (float x)
Variables
float(* ntact_activation [NTACT_TOTAL_FUNCTIONS][2])(float)
Activation dispatch table.
float ntact_rand_range [NTACT_TOTAL_FUNCTIONS][2]
Random initialization range table for activation functions.
Detailed Description
Internal implementation of activation behavior.
Author
Oscar Sotomayor (Titux)
This file provides the concrete implementation of activation functions and their derivatives used by the NeuroTIC execution context.
It defines the internal activation dispatch tables and the recommended initialization ranges associated with each activation.
This file does not define public contracts. All external access is mediated through ntactivation.h.
Activation execution model
The activation subsystem implements a stateless execution model for scalar transformations.
A fixed set of activation operations is defined and resident in memory. Each operation can be selected and evaluated independently.
Execution is defined by three elements:
Activation selector Identifies the operation to be evaluated.
Operation mode Selects between the activation function or its derivative.
Input operand The scalar value provided for evaluation.
No internal state is preserved between evaluations. All operations are pure and deterministic.
Access to activation behavior is performed exclusively through the activation dispatch table.
Definition in file ntactivation.c.
Function Documentation
boolean()
static float boolean (float x) static
boolean_d()
static float boolean_d (float x) static
sigmoid()
static float sigmoid (float x) static
Referenced by sigmoid_d().
sigmoid_d()
static float sigmoid_d (float x) static
References sigmoid().
Variable Documentation
ntact_activation
float(* ntact_activation[NTACT_TOTAL_FUNCTIONS][2])(float) (float)
Initial value:
={
    [NTACT_BOOLEAN]= { boolean , boolean_d },
    [NTACT_SIGMOID]= { sigmoid , sigmoid_d }
}
Activation dispatch table.
Defines the mapping between activation identifiers and their associated execution functions. Indexing:
First index : activation identifier
Second index : [0] activation [1] derivative
Referenced by activate().
ntact_rand_range
float ntact_rand_range[NTACT_TOTAL_FUNCTIONS][2]
Initial value:
={
    [NTACT_BOOLEAN]= { -1.0f , 1.0f },
    [NTACT_SIGMOID]= { -1.0f , 1.0f }
}
Random initialization range table for activation functions.
Random initialization range table for activation functions.
Defines the preferred initialization range associated with each activation function.
Referenced by randnet().