NeuroTIC: /home/titux/DEV/NeuroTIC/NeuroTIC/include/CPU/ntbuilder.h File Reference
ntbuilder.h File Reference
Construction Functions.
http://tituxdev.github.io/NeuroTIC/src/CPU/ntbuilder.c.
#include "ntcore.h"
#include <stddef.h>
Macros
#define NEWNET(network, neurons) newnet(network, neurons, (layer_t)sizeof(neurons)/sizeof(uint16_t))
Convenience macro to create a new network.
#define CREATE_NET_FEEDFORWARD(network, i, neurons)
Convenience macro to declare, build, and wire a new feedforward network in a single step.
Functions
struct net_s * newnet (net_s *net, uint16_t *neurons_per_layer, layer_t layers_size)
Allocates and initializes net_s internal structures from a per-layer neuron count.
struct net_s * buildnet (net_s *net)
Resolves wiring descriptors into buffer references and allocates weight storage.
Detailed Description
Construction Functions.
http://tituxdev.github.io/NeuroTIC/src/CPU/ntbuilder.c.
Provides memory allocation and pointer setup for neurons, input/output references, and inter-layer buffers.
Uses memtrack() to manage memory safely.
Author
Oscar Sotomayor
Date
2026
Definition in file ntbuilder.h.
Macro Definition Documentation
CREATE_NET_FEEDFORWARD
#define CREATE_NET_FEEDFORWARD (network, i, neurons)
Value:
    net_s *network= &(net_s){ \
        .inputs= i, \
        .layers= sizeof( neurons )/sizeof( uint16_t ), \
    }; \
    buildnet( newfeedforward( NEWNET( network , neurons ) ) );
Convenience macro to declare, build, and wire a new feedforward network in a single step.
Expands to a variable declaration followed by its construction: declares network as a new net_s * in the calling scope, then builds and wires it as a fully-connected feedforward network. Because it expands to a declaration, it can only be used as a standalone statement – never as part of a larger expression.
Parameters
network Identifier to declare as the new network variable.
i Number of external inputs to the network.
neurons Array defining the number of neurons in each layer.
NEWNET
#define NEWNET (network, neurons) newnet(network, neurons, (layer_t)sizeof(neurons)/sizeof(uint16_t))
Convenience macro to create a new network.
Simplifies calling newnet() by automatically calculating the number of layers from the neurons array size.
Parameters
network Pointer to the network structure to initialize.
neurons Array defining the number of neurons per layer.
Returns
net_s Pointer to the initialized network on success, or NULL on failure.
Function Documentation
buildnet()
struct net_s * buildnet (net_s * net)
Resolves wiring descriptors into buffer references and allocates weight storage.
Parameters
net Network with wiring descriptors already defined.
Returns
The same net pointer, for call chaining.
Return values
NULL
net is NULL.
net->neurons has not been allocated yet.
If net_s::layers > 1, resolves each net_s::wiring descriptor into a net_s::bff array for its corresponding layer transition (net->bff[0..layers-2]), in two passes:
First pass: for arrays with wiring_s::array_type ‘'M’`, each element is resolved individually according to its own wiring_s::src_type.
Second pass: for all other arrays, the whole array is resolved at once according to its wiring_s::array_type, and wiring_s::size is updated to match the resolved size. Layer 0 is not processed by either pass.
Then, for every neuron from layer 1 onward, sets neuron_s::in and neuron_s::inputs from the net_s::bff / wiring_s::size entry selected by its neuron_s::bff_idx.
Finally, allocates neuron_s::w for every neuron in the network according to its (resolved or pre-existing) neuron_s::inputs.
Note
wiring_s::array_type (second pass):
'I': Alias to net_s::in.
'O': Alias to net_s::out.
'N': Alias to another already-resolved net_s::bff array, referenced by this array's own wiring_s::src_layer[0] and wiring_s::src_index[0].
any other value: left as NULL, with a placeholder size of 1.
wiring_s::src_type, for elements inside a ‘'M’‘ array (first pass):
'N’: net->nn[src_layer][src_index].out.
'O': A single element of net_s::out.
any other value: left as NULL.
References wiring_s::array_type, wiring_s::arrays, net_s::bff, neuron_s::bff_idx, neuron_s::in, net_s::in, neuron_s::inputs, net_s::inputs, net_s::layers, net_s::neurons, net_s::nn, neuron_s::out, net_s::out, wiring_s::size, wiring_s::src_index, wiring_s::src_layer, wiring_s::src_type, and net_s::wiring.
Referenced by definetopology(), and loadnet().
newnet()
struct net_s * newnet (net_s * net, uint16_t * neurons_per_layer, layer_t layers_size)
Allocates and initializes net_s internal structures from a per-layer neuron count.
Parameters
net Network with net_s::inputs and net_s::layers already set.
neurons_per_layer Array of per-layer neuron counts, size layers_size.
layers_size Must equal net->layers.
Returns
The same net pointer received, with its internal structures allocated and initialized.
Return values
NULL
net or neurons_per_layer is NULL.
net_s::layers is less than 1.
layers_size does not match net_s::layers.
any per-layer neuron count is less than 1.
Copies neurons_per_layer into net_s::neurons and allocates net_s::nn with one neuron_s array per layer.
Allocates net_s::in and connects it to the first layer's neurons, and allocates net_s::out pointing to the last layer's neuron outputs.
When net_s::layers is greater than 1, allocates one net_s::wiring descriptor per layer transition, and net_s::bff's outer array (one slot per layer transition, each left as NULL).
References neuron_s::in, net_s::in, neuron_s::inputs, net_s::inputs, net_s::layers, net_s::neurons, net_s::nn, neuron_s::out, and net_s::out.
Referenced by definestructure(), and loadnet().