NeuroTIC: /home/titux/DEV/NeuroTIC/NeuroTIC/include/CPU/ntcalculate.h File Reference
ntcalculate.h File Reference
Execution and Training
Implementation of feedforward network computations.
#include "ntcore.h"
Functions
data_t weighing (neuron_s *neuron)
Computes the weighted sum of a neuron.
data_t activate (neuron_s *neuron)
Applies the configured activation function.
data_t ** feedforward (net_s *net)
Executes full feedforward propagation.
Detailed Description
Implementation of feedforward network computations.
https://tituxdev.github.io/NeuroTIC/src/CPU/ntcalculate.c
Provides weighted sum, activation, and full forward propagation.
Assumes sequential layer-by-layer calculation.
Author
Oscar Sotomayor
Date
2026
Definition in file ntcalculate.h.
Function Documentation
activate()
data_t activate (neuron_s * neuron)
Applies the configured activation function.
Parameters
neuron Pointer to the neuron.
Returns
Activated output value.
Activation functions are resolved from the global ntact_activation lookup table using the neuron's configured activation identifier.
Result is stored in the neuron's out field.
Todo:
neuron_s::fn is not validated against NTACT_TOTAL_FUNCTIONS before indexing ntact_activation – behavior for an out-of-range value is undefined until a validation strategy (and how tightly coupled it should be with other modules) is decided.
References neuron_s::fn, ntact_activation, neuron_s::out, and weighing().
Referenced by feedforward().
feedforward()
data_t ** feedforward (net_s * net)
Executes full feedforward propagation.
Parameters
net Pointer to a net_s instance whose base structure has already been built.
Returns
The network's own output array (net_s::out), with every neuron's output freshly computed.
Todo:
net_s::in is not validated before use – if every external input has been set to NULL (e.g. after training releases its own input buffer), this function will dereference a NULL pointer instead of failing predictably. Add a check for every net_s::in[i] before computing.
Return values
NULL net is NULL.
Iterates layer-by-layer to maintain deterministic ordering. Before evaluating a neuron, re-resolves any ‘'I’-typed element nested inside its selected'M'buffer against the network's currentnet_s::in-- every other wiring reference was already resolved once, permanently, by buildnet()`. All other buffer entries are read as-is via their existing pointer connections.
References activate(), wiring_s::array_type, net_s::bff, neuron_s::bff_idx, net_s::in, neuron_s::inputs, net_s::layers, net_s::neurons, net_s::nn, net_s::out, wiring_s::src_index, wiring_s::src_type, and net_s::wiring.
Referenced by backpropagation().
weighing()
data_t weighing (neuron_s * neuron)
Computes the weighted sum of a neuron.
Parameters
neuron Pointer to the neuron.
Returns
Weighted sum including bias.
Calculates the weighted sum of a neuron by iterating over its inputs and weights.
weighted_sum = Σ(input_i * weight_i) + bias
The bias term is accumulated first to reduce one addition inside the loop.
Inputs are assumed to be valid pointers.
References neuron_s::b, neuron_s::in, neuron_s::inputs, and neuron_s::w.
Referenced by activate().