NeuroTIC: /home/titux/DEV/NeuroTIC/NeuroTIC/src/CPU/ntfile.c File Reference
ntfile.c File Reference
Implementation of network persistence for NeuroTIC.
#include "ntfile.h"
#include "ntbuilder.h"
#include "ntmemory.h"
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>
#include <float.h>
Data Structures
struct float_parts_s
Macros
#define NAME_LENGTH 30
#define MAGIC "NeuroTIC"
#define VERSION 0x0
#define STRICT_LE16(x) &(uint16_t){ little_endian ? (x) : bswap16(x)}
#define STRICT_LE32(x) &(uint32_t){ little_endian ? (x) : bswap32(x)}
Functions
uint8_t checkendian (void)
uint16_t bswap16 (uint16_t x)
uint32_t bswap32 (uint32_t x)
uint8_t isieee754 (void)
uint32_t float32 (float x, uint8_t ieee754)
float floatsys (int32_t x, uint8_t ieee754)
unsigned char savenet (net_s *net, const char *name)
Saves a network to disk in binary format.
struct net_s loadnet (char *name)
Loads a network from a binary file.
Detailed Description
Implementation of network persistence for NeuroTIC.
Supports saving and loading network structures to binary .ntic files.
Pending: data standardization, validation checks, and error handling.
Author
Oscar Sotomayor
Date
2024
Definition in file ntfile.c.
Macro Definition Documentation
MAGIC
#define MAGIC "NeuroTIC"
NAME_LENGTH
#define NAME_LENGTH 30
STRICT_LE16
#define STRICT_LE16 (x) &(uint16_t){ little_endian ? (x) : bswap16(x)}
STRICT_LE32
#define STRICT_LE32 (x) &(uint32_t){ little_endian ? (x) : bswap32(x)}
VERSION
#define VERSION 0x0
Function Documentation
bswap16()
uint16_t bswap16 (uint16_t x)
Referenced by loadnet().
bswap32()
uint32_t bswap32 (uint32_t x)
Referenced by loadnet().
checkendian()
uint8_t checkendian (void)
Referenced by loadnet(), and savenet().
float32()
uint32_t float32 (float x, uint8_t ieee754)
References float_parts_s::e, float_parts_s::m, and float_parts_s::sign.
floatsys()
float floatsys (int32_t x, uint8_t ieee754)
References float_parts_s::e, float_parts_s::m, and float_parts_s::sign.
Referenced by loadnet().
isieee754()
uint8_t isieee754 (void)
Referenced by loadnet(), and savenet().
loadnet()
struct net_s loadnet (char * name)
Loads a network from a binary file.
Loads a network from a binary file with extension .ntic.
Reconstructs all network data and buffer wiring. Currently does not validate the file or perform data standardization.
Parameters
name Base filename to load (extension .ntic will be added).
Returns
The reconstructed network.
References wiring_s::array_type, wiring_s::arrays, neuron_s::b, neuron_s::bff_idx, bswap16(), bswap32(), buildnet(), checkendian(), floatsys(), neuron_s::fn, neuron_s::inputs, net_s::inputs, isieee754(), net_s::layers, net_s::neurons, newnet(), net_s::nn, wiring_s::size, wiring_s::src_index, wiring_s::src_layer, wiring_s::src_type, neuron_s::w, and net_s::wiring.
savenet()
unsigned char savenet (net_s * net, const char * name)
Saves a network to disk in binary format.
Saves a network to a binary file with extension .ntic.
Writes the network structure, weights, biases, and buffer wiring.
Parameters
net Pointer to the network to save.
name Base filename to save (extension .ntic will be added).
Returns
0 on success.
References wiring_s::array_type, wiring_s::arrays, checkendian(), neuron_s::fn, neuron_s::inputs, isieee754(), net_s::layers, net_s::neurons, net_s::nn, wiring_s::size, wiring_s::src_type, and net_s::wiring.
Referenced by main().