NeuroTIC: /home/titux/DEV/NeuroTIC/NeuroTIC/include/CPU/ntfile.h File Reference
ntfile.h File Reference
Save and load NeuroTIC networks to/from binary files.
#include "ntcore.h"
Functions
unsigned char savenet (net_s *net, const char *name)
Saves a network to a binary file with extension .ntic.
struct net_s loadnet (char *name)
Loads a network from a binary file with extension .ntic.
Detailed Description
Save and load NeuroTIC networks to/from binary files.
Provides functions to persist network structures and weights, allowing training to be stored and reloaded.
Author
Oscar Sotomayor
Date
2024
Definition in file ntfile.h.
Function Documentation
loadnet()
struct net_s loadnet (char * name)
Loads a network from a binary file with extension .ntic.
Reconstructs the network structure, weights, biases, and buffer wiring. Currently, data standardization and validation are not integrated.
Parameters
name Base filename (without extension) of the saved network.
Returns
The loaded network structure.
Loads a network from a binary file with extension .ntic.
Reconstructs all network data and buffer wiring. Currently does not validate the file or perform data standardization.
Parameters
name Base filename to load (extension .ntic will be added).
Returns
The reconstructed network.
References wiring_s::array_type, wiring_s::arrays, neuron_s::b, neuron_s::bff_idx, bswap16(), bswap32(), buildnet(), checkendian(), floatsys(), neuron_s::fn, neuron_s::inputs, net_s::inputs, isieee754(), net_s::layers, net_s::neurons, newnet(), net_s::nn, wiring_s::size, wiring_s::src_index, wiring_s::src_layer, wiring_s::src_type, neuron_s::w, and net_s::wiring.
savenet()
unsigned char savenet (net_s * net, const char * name)
Saves a network to a binary file with extension .ntic.
Stores the network's layers, neurons, weights, biases, and buffer wiring.
Parameters
net Pointer to the network to save.
name Base filename (without extension) to save the network.
Returns
0 on success, non-zero on failure (future validation to be added).
Saves a network to a binary file with extension .ntic.
Writes the network structure, weights, biases, and buffer wiring.
Parameters
net Pointer to the network to save.
name Base filename to save (extension .ntic will be added).
Returns
0 on success.
References wiring_s::array_type, wiring_s::arrays, checkendian(), neuron_s::fn, neuron_s::inputs, isieee754(), net_s::layers, net_s::neurons, net_s::nn, wiring_s::size, wiring_s::src_type, and net_s::wiring.
Referenced by main().