NeuroTIC: /home/titux/DEV/NeuroTIC/NeuroTIC/src/CPU/ntmemory.c File Reference
ntmemory.c File Reference
Implementation of memory management functions.
#include "ntmemory.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <search.h>
Data Structures
struct mem_format
Functions
int match_owner (const void *key, const void *element)
int match_register (const void *key, const void *element)
void cleanmemory (void)
Deletes a memory block from the tracking registry and frees it.
unsigned char deleteowner (void *owner)
Deletes a memory owner and all associated memory blocks.
void * createowner (void *owner)
Creates a memory owner and registers it in the tracking system.
void * createregister (void *owner, void *mem)
Creates a memory register entry for a specific memory owner.
Variables
struct mem_format * mem_tracker = NULL
size_t mem_track = 0
Detailed Description
Implementation of memory management functions.
Provides functions for tracking dynamically allocated memory blocks and ensuring they are freed at program termination.
Uses a dynamic registry to store pointers to allocated memory, and registers a cleanup function with atexit() to automatically free all tracked memory when the program exits.
Author
Oscar Sotomayor.
Date
2026
Definition in file ntmemory.c.
Function Documentation
cleanmemory()
void cleanmemory (void)
Deletes a memory block from the tracking registry and frees it.
Iterates through the mem_tracker array and frees all memory blocks registered under each memory owner.
After freeing the memory blocks, it also frees the memory register and resets the tracking information for each owner.
Finally, it frees the entire mem_tracker array and resets the tracking counter.
This function is registered with atexit() to ensure that all tracked memory is automatically freed when the program exits, preventing memory leaks and ensuring proper cleanup of resources.
It is important to note that this function should not be called manually, as it is designed to be invoked automatically.
Warning
This function should not be called manually, as it is designed to be invoked automatically at program termination. Calling it manually may lead to unintended consequences, such as double freeing memory or leaving dangling pointers if the tracking system is still in use.
Attention
This function assumes that all memory blocks registered in the tracking system were allocated using malloc() or similar functions and can be safely freed.
See also
deleteowner() for deleting a specific memory owner and its associated memory blocks.
References mem_track.
Referenced by createowner(), and deleteowner().
createowner()
void * createowner (void * owner)
Creates a memory owner and registers it in the tracking system.
Return values
NULL if the provided owner pointer is NULL, or if memory allocation fails during the creation of a new memory owner.
Pointer to the created memory owner if successful, or a pointer to the existing owner if it already exists in the tracking system.
This function creates a new memory owner and registers it in the tracking system.
If the owner already exists, it returns a pointer to the existing owner.
The function ensures that each memory owner is uniquely tracked within the system. If the provided owner pointer is NULL, the function returns NULL without creating a new owner.
References cleanmemory(), and mem_format::mem_owner.
Referenced by createregister().
createregister()
void * createregister (void * owner, void * mem)
Creates a memory register entry for a specific memory owner.
Return values
void* Pointer to the registered memory block.
NULL if the provided owner block pointer is NULL.
owner pointer if mem is NULL
Search for te existence of the provided memory owner in the tracking system. If the owner does not exists:
Increases the size of regisgter table.
Creates a new memory owner and registers it in the tracking system. If the owner exists:
Search for the existence of the provided memory block in the owner's register.
If the memory block does not exist, it is added to the owner's register.
If the memory block already exists, a pointer to the existing block is returned.
References createowner(), and mem_format::mem_register.
deleteowner()
unsigned char deleteowner (void * owner)
Deletes a memory owner and all associated memory blocks.
Parameters
owner Pointer to the memory owner to delete.
Return values
0 Success, owner not found.
1 owner parameter is NULL.
2 register allocation failed
This function deletes a specific memory owner and all associated memory blocks from the tracking system.
It first checks if the provided owner pointer is valid, then searches for the owner in the mem_tracker array. If the owner is found, it frees all memory blocks registered under that owner, frees the memory register, and removes the owner from the tracking system.
The function returns 0 if the deletion is successful, 1 if the owner is not found, and 2 if memory allocation fails during the process.
See also
If is the last register in mem_tracker, cleanmemory() is called.
References cleanmemory(), mem_format::mem_register, and mem_track.
match_owner()
int match_owner (const void * key, const void * element)
Parameters
key Pointer to the memory owner to match.
element Pointer to the memory format element being compared.
Return values
0 if the owner matches the element's memory owner, non-zero otherwise.
1 if the provided key is NULL, or if the element's memory owner is NULL.
This function is used as a comparison function for searching the mem_tracker array to find the index of a specific memory owner.
It compares the provided key (memory owner) with the mem_owner field of the memory format element.
A return value of 0 indicates a match (i.e., the owner is found), while a non-zero return value indicates that the owner does not match the element being compared.
This function is essential for managing memory ownership and ensuring that memory blocks are correctly associated with their respective owners in the tracking system.
References mem_format::mem_owner.
match_register()
int match_register (const void * key, const void * element)
This function is used as a comparison function for searching the mem_tracker array to find the index of a specific memory register entry.
It compares the provided key (memory register entry) with the mem_register field of the memory format element.
A return value of 0 indicates a match (i.e., the register entry is found), while a non-zero return value indicates that the register entry does not match the element being compared.
This function is essential for managing memory ownership and ensuring that memory blocks are correctly associated with their respective owners in the tracking system.
Variable Documentation
mem_track
size_t mem_track = 0
Increases as new memory owners are created and memory blocks are registered under those owners. Decreases as memory owners are deleted and their associated memory blocks are freed. This counter is essential for managing the dynamic array of mem_format structures, ensuring that memory ownership and tracking are accurately maintained throughout the lifecycle of the program.
Warning
This counter must be carefully managed to prevent memory leaks or dangling pointers.
Referenced by cleanmemory(), and deleteowner().
mem_tracker
struct mem_format * mem_tracker = NULL