NeuroTIC: /home/titux/DEV/NeuroTIC/NeuroTIC/include/CPU/ntmemory.h File Reference
ntmemory.h File Reference
Memory Management Functions
http://tituxdev.github.io/NeuroTIC/src/CPU/ntmemory.c.
Functions
void cleanmemory (void)
Deletes a memory block from the tracking registry and frees it.
unsigned char deleteowner (void *owner)
Deletes a memory owner and all associated memory blocks.
void * createowner (void *owner)
Creates a memory owner and registers it in the tracking system.
void * createregister (void *owner, void *mem)
Creates a memory register entry for a specific memory owner.
Detailed Description
Memory Management Functions
http://tituxdev.github.io/NeuroTIC/src/CPU/ntmemory.c.
Provides functions for tracking dynamically allocated memory blocks and ensuring they are freed at program termination.
Uses a dynamic registry to store pointers to allocated memory, and registers a cleanup function with atexit() to automatically free all tracked memory when the program exits.
Author
Oscar Sotomayor.
Date
2026
Definition in file ntmemory.h.
Function Documentation
cleanmemory()
void cleanmemory (void)
Deletes a memory block from the tracking registry and frees it.
Iterates through the mem_tracker array and frees all memory blocks registered under each memory owner.
After freeing the memory blocks, it also frees the memory register and resets the tracking information for each owner.
Finally, it frees the entire mem_tracker array and resets the tracking counter.
This function is registered with atexit() to ensure that all tracked memory is automatically freed when the program exits, preventing memory leaks and ensuring proper cleanup of resources.
It is important to note that this function should not be called manually, as it is designed to be invoked automatically.
Warning
This function should not be called manually, as it is designed to be invoked automatically at program termination. Calling it manually may lead to unintended consequences, such as double freeing memory or leaving dangling pointers if the tracking system is still in use.
Attention
This function assumes that all memory blocks registered in the tracking system were allocated using malloc() or similar functions and can be safely freed.
See also
deleteowner() for deleting a specific memory owner and its associated memory blocks.
References mem_track.
Referenced by createowner(), and deleteowner().
createowner()
void * createowner (void * owner)
Creates a memory owner and registers it in the tracking system.
Parameters
owner Pointer to the memory owner to create.
Returns
void* Pointer to the created memory owner, or NULL if creation fails.
Parameters
owner Pointer to the memory owner to create.
Returns
void* Pointer to the created memory owner, or NULL if creation fails.
owner Pointer to the existing memory owner if it already exists.
NULL if the provided owner pointer is NULL.
This function creates a new memory owner and registers it in the tracking system.
If the owner already exists, it returns a pointer to the existing owner.
The function ensures that each memory owner is uniquely tracked within the system. If the provided owner pointer is NULL, the function returns NULL without creating a new owner.
See also
createregister() for creating a memory register entry for a specific memory owner and memory block.
References cleanmemory(), and mem_format::mem_owner.
Referenced by createregister().
createregister()
void * createregister (void * owner, void * mem)
Creates a memory register entry for a specific memory owner.
Parameters
owner Pointer to the memory owner.
mem Pointer to the memory block to register.
Returns
void* Pointer to the created register entry, or NULL if creation fails.
Parameters
owner Pointer to the memory owner.
mem Pointer to the memory block to register.
Returns
void* Pointer to the registered memory block.
NULL if the provided owner or memory block pointer is NULL.
Search for te existence of the provided memory owner in the tracking system. If the owner does not exists:
Increases the size of regisgter table.
Creates a new memory owner and registers it i
See also
createowner() for creating a memory owner and registering it in the tracking system. deleteowner() for deleting a specific memory owner and its associated memory blocks. cleanmemory() for freeing all memory blocks registered in the tracking system at program termination.
References createowner(), and mem_format::mem_register.
deleteowner()
unsigned char deleteowner (void * owner)
Deletes a memory owner and all associated memory blocks.
Parameters
owner Pointer to the memory owner to delete.
Returns
unsigned char 0 if successful, 1 if the owner is not found, 2 if memory allocation fails.
Parameters
owner Pointer to the memory owner to delete.
Return values
0 Sucess, owner not found.
1 owner is NULL.
2 register allocation failed
This function deletes a specific memory owner and all associated memory blocks from the tracking system.
It first checks if the provided owner pointer is valid, then searches for the owner in the mem_tracker array. If the owner is found, it frees all memory blocks registered under that owner, frees the memory register, and removes the owner from the tracking system.
The function returns 0 if the deletion is successful, 1 if the owner is not found, and 2 if memory allocation fails during the process.
See also
If is the last register in mem_tracker, cleanmemory() is called.
References cleanmemory(), mem_format::mem_register, and mem_track.