NeuroTIC: /home/titux/DEV/NeuroTIC/NeuroTIC/workspace/test.c File Reference
test.c File Reference
#include "test.h"
#include "ntcomplete.h"
Macros
#define NETWORK_NAME test
#define OUTPUT_DIR "./test_net.nt"
#define INPUTS 2
#define NEURONS_PER_LAYER 3,16
#define ACTIVATION_FUNCTIONS NTACT_SIGMOID
#define TRAINING_SAMPLES 4
#define LEARNING_RATE 0.1
#define TOLERANCE 0.0
#define MAX_ATTEMPTS 10000000
Functions
int main (void)
Macro Definition Documentation
ACTIVATION_FUNCTIONS
#define ACTIVATION_FUNCTIONS NTACT_SIGMOID
INPUTS
#define INPUTS 2
LEARNING_RATE
#define LEARNING_RATE 0.1
MAX_ATTEMPTS
#define MAX_ATTEMPTS 10000000
NETWORK_NAME
#define NETWORK_NAME test
NEURONS_PER_LAYER
#define NEURONS_PER_LAYER 3,16
OUTPUT_DIR
#define OUTPUT_DIR "./test_net.nt"
TOLERANCE
#define TOLERANCE 0.0
TRAINING_SAMPLES
#define TRAINING_SAMPLES 4
Function Documentation
main()
int main (void)
References backpropagation(), feedforward(), neuron_s::fn, net_s::in, nttraindata::in, net_s::inputs, net_s::layers, nttraindata::learning_rate, nttraindata::max_attempts, net_s::neurons, newtraindata(), net_s::nn, net_s::out, randnet(), nttraindata::results, nttraindata::samples, savenet(), and nttraindata::tolerance.